build:
  cuda_version: "12.1.1"
  system_packages:
    - "libssl-dev"
    - "libx11-6"
    - "libxext6"
    - "libgl1-mesa-glx"
  python_packages:
    - "torch==1.13.1"
    - "diffusers==0.23.1"
    - "transformers==4.35.1"
    - "accelerate==0.23.0"
    - "safetensors==0.4.0"
    - "invisible-watermark==0.2.0"
    - "xformers==0.0.16"
